- name: Reboot System
  hosts: all
  tasks:
    - name: Reboot System
      command: systemctl reboot -i 
    - name: Wait for system to become reachable after reboot
      local_action: 
        wait_for host={{ ansible_ssh_host }} state=started


