- name: Yum Update all
  hosts: all
  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
      msg: "System up to date"
    - name: Reboot System
      command: 'systemctl reboot -i' 
      msg: "System rebooting"
