- name: Yum Update all
  hosts: all
  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
    - name: Reboot System
      command: 'systemctl reboot -i' 
      local_action: wait_for host={{ ansible_ssh_host }} state=started 
